refactor: make underlying default
bgd-labs/static-a-token-v3 pull request #45
Opened 2023-08-04 10:13 UTC by sakulstra

2023-08-07 09:38 UTC, sakulstra commented on src/StaticATokenLM.sol
> -    uint256 staticAmount,
renamign to be more inline with the rest of the wording

2023-08-07 10:55 UTC, sakulstra commented on src/StaticATokenLM.sol
>    function _deposit(
I'm not so sure about this change - essentially aligned with `_withdraw`

2023-08-09 06:20 UTC, eboadom commented
@sakulstra I think we should also rename the `fromUnderlying` and `toUnderlying` to something clearer, and respecting how the interface worked.
Maybe `depositToAave` and `withdrawFromAave`?
The rationale is to keep pointing out integrators to the non-4626 functions, and having that interface not losing compatibility

2023-08-09 07:34 UTC, kyzia551 requested changes

2023-08-09 07:34 UTC, kyzia551 commented on src/StaticATokenLM.sol
> +    return assets == 0 ? 0 : _convertToShares(assets, Rounding.DOWN);
I would either remove this ternary operator completely or move it inside _convertToShares. But better to remove imo

2023-08-09 07:34 UTC, kyzia551 commented on src/StaticATokenLM.sol
> +    return shares == 0 ? 0 : _convertToAssets(shares, Rounding.DOWN);
I would either remove this ternary operator completely or move it inside _convertToAssets. But better to remove IMO. Now does not look consistent with other usages

2023-08-09 10:28 UTC, kyzia551 approved these changes

2023-08-09 19:18 UTC, merged